### ISSUE TITLE
Issue with plotRaster (and plotTracks)

### ISSUE THREAD

**Issue by Jet2191** [hugomflavio/actel#100]
Hi, 
On your website you write 'Some water may show up around the edges of the original shapefile due to the range adjustments made by shapeToRaster.' This is happening for me (maybe also because my shape file is a little bit tilted? 
Anyway because of the water around the edges the tracks are plotted around the edges of the map instead of through the actual rivers.
![image](https://github.com/user-attachments/assets/f8bd90fe-2203-461d-9ff9-a2a9c31dcf05)
![Track V29 July](https://github.com/user-attachments/assets/70b86852-7627-4938-9dee-adb7563b418b)
How can I fix this? 
Kind regards, 
Jet

**Comment by hugomflavio** [comment]
Hi Jet,

Would it be an option to correct the original shapefile so it cuts cleanly into a square on geographic coordinates?

The tilting is indeed what led to the first issue. You could also prevent that by modifying the shapefile slightly and cutting the rivers off with a bit of land on the upstream side. That way the model will have no choice but to flow down.

The RSP error seems likely related to the shapefile issues too, though I am not quite sure what that error means. That part of the question is most likely better off posted at the RSP repository.

But my first bet would be to trim/edit the shapefile a bit so it fits nicely to begin with. Let me know if you need help with that.

**Comment by hugomflavio** [comment]
Inactive, closing.
