### ISSUE TITLE
manual starting point should be made more clear in webpage

### ISSUE THREAD

**Issue by hugomflavio** [hugomflavio/actel#107]
Users who land on the webpage may have trouble finding out how to actually start to work with the package

**Comment by SimonDedman** [comment]
At the bottom of the [home page](https://hugomflavio.github.io/actel-website/index.html), add a "Start [HERE](https://hugomflavio.github.io/actel-website/manual-index.html)" link

**Comment by hugomflavio** [comment]
New button added to the website homepage :+1:

**Comment by SimonDedman** [comment]
Nice work!
