### ISSUE TITLE
Add functions to pre-check input tables before preload

### ISSUE THREAD

**Issue by SimonDedman** [hugomflavio/actel#128]
Would obviate issues such as [this](https://hugomflavio.github.io/actel-website/index.html);

Currently the workflow is:

1. Run through script to prepare all tables: spatial, deployments, etc.
2. Run preload
3. Discover error (your error documentation & prompting is EXCELLENT btw mate, hats off)
4. Go back up, fix error
5. Goto 1

With functions like `checkSpatial` (etc), the workflow would be

1. Run through script to prepare table 1 e.g. biometrics
2. Run e.g. `checkBiometrics`
3. Discover error
4. Fix error
5. Repeat 1-4 for each script
6. Run preload

Conceptually you already have the code for all of these functions boiled into `preload`, which you wouldn't need to remove.

**Comment by hugomflavio** [comment]
I can see the value in this. However, we are currently working towards a system where the function that loads the object also tests for the quality of the object right away, so I don't think it makes sense for me to add this to actel now. The new system will allow e.g. adding the `biometrics` table to your `study` object and have the `biometrics` checked right away (not just by itself, but against any other data present in the `study` object).

@jdpye and @jackVanish this one is relevant for surimi.

**Comment by SimonDedman** [comment]
Sounds cool, cheers!
