### ISSUE TITLE
Stations not present in distances matrix

### ISSUE THREAD

**Issue by SimonDedman** [hugomflavio/actel#150]
[moved here from #147 ]

Previous chat:

> Warning: Some stations and/or release sites are not present in the distances matrix. Deactivating speed calculations to avoid function failure. Stations missing: 'St.1', [...], 'St.127

Where is it (not) getting these station names from?

> This distances matrix is not correctly formatted for actel. How was it made?

```
install.packages("gbm.auto")
library(gbm.auto)
gbm.auto::gbm.basemap(bounds = c(min(spatial$Longitude),
                                 max(spatial$Longitude),
                                 min(spatial$Latitude),
                                 max(spatial$Latitude)),
                      savedir = file.path(loadloc, "actel", "NOAAcoastlines"),
                      getzip = file.path(loadloc, "actel", "NOAAcoastlines"),
                      extrabounds = FALSE)
# install.packages("gdistance")
base.raster <- actel::shapeToRaster(shape = file.path(loadloc, "actel", "NOAAcoastlines", "CroppedMap", "Crop_Map.shp"),
                                    size = 0.01, # of the raster pixels in metres (or possibly 100km's)
                                    spatial = spatial, # " character string specifying the path to a spatial.csv file or a spatial data frame
                                    coord.x = "Longitude", # names of the columns containing the x and y coordinates
                                    coord.y = "Latitude",
                                    buffer = NULL) # request an expansion of the shapefile limits
t.layer <- actel::transitionLayer(base.raster, directions = 16)
distances <- actel::distancesMatrix(
  t.layer = t.layer,
  starters = spatial,
  targets = spatial,
  coord.x = "Longitude",
  coord.y = "Latitude",
  # id.col = "Station.name",
  actel = FALSE
)
# Colnames & rownames don't match due to Xs, remove GNWR dupe & rename:
duperowremove <- max(which(spatial$Station.name == "GNWR"), na.rm = TRUE)
distances <- distances[-duperowremove,] # remove column
distances <- distances[,-duperowremove] # remove row
colnames(distances) <- unique(spatial$Station.name)
rownames(distances) <- unique(spatial$Station.name)

```

> the actel = false argument is the issue. @dsmith-unbc what is the status on the distanceMatrix updates you were working on? I think they would solve this by letting Simon use the starter argument while actel = true. If there's something I should be doing on that front and I forgot, let me know 😄

where are the "St.1" station names coming from? Until this point it seems like everything is contained in the 5 files, but St.1 isn't anywhere...

> I should be able to get the distanceMatrix updated code pushed by Friday.

**Comment by SimonDedman** [comment]
> Warning: Tag 9001-52509 (5/13) jumped through 4 arrays from release to first valid event (Release -> West_Palm_Beach).

Given my array:

![image](https://github.com/user-attachments/assets/d78255e9-0c14-4816-b449-0d9ad2040c4e)

Are these warnings relevant? Can I ignore them? Should I setup my array/distances differently?

Thanks!

**Comment by hugomflavio** [comment]
@SimonDedman did you set up a spatial.txt file? It would be a tough one considering how many connections there will be. The burden of mapping the connections of mostly-open systems is actually something I've discussed with @jdpye on a few occasions and which we're aiming to alleviate in the next round of big updates.

**Comment by SimonDedman** [comment]
I have a spatial file with locations, a distances file, etc. I followed all the steps, but it occurs to me that the guidance might be more geared to the example of a closed river system than an open ocean system. And maybe that just means I can ignore the warnings about jumping through arrays?

But I would like to get the distances things sorted via fixing the station names issue, so that actel can use the speed filter to test suspicious jumps.

**Comment by hugomflavio** [comment]
The [spatial.txt](https://hugomflavio.github.io/actel-website/manual-data.html#spatial-txt) file and the [spatial.csv](https://hugomflavio.github.io/actel-website/manual-data.html#spatial-file) file are two different inputs.

From your screenshots on issue #152, it seems you didn't set up a spatial.txt file? Without that, actel will get rather confused by your study area.

**Comment by SimonDedman** [comment]
oy vey, I'd completely forgotten about that!

I presume with an open array, I should have a row connecting each combination of pairs of stations, one by one?

Thanks!

**Comment by hugomflavio** [comment]
@SimonDedman #145 was just merged into the master development branch. The distancesMatrix can now accept a spatial object as a `starters` input _and_ keep `actel = TRUE` at the same time. This should solve your issues about the distances matrix not having the right column/row names.

To install the dev version:

```r
# If you don't have the package "remotes" installed, start with:
install.packages("remotes")

# This will install actel's development version:
remotes::install_github("hugomflavio/actel"
                        build_opts = c("--no-resave-data", "--no-manual"), 
                        build_vignettes = TRUE)

library("actel")
# The displayed version should now be 1.3.0.9016 (or higher)
# If that is not the case, unload actel and load it again.
```

**Comment by SimonDedman** [comment]
Thanks folks. For the following, then:

```
distances <- actel::distancesMatrix(
  t.layer = t.layer,
  starters = spatial,
  targets = spatial,
  coord.x = "Longitude",
  coord.y = "Latitude",
  id.col = "Station.name",
  actel = TRUE
)
```

I'm getting:

> Error: 'starters' is missing column called 'Standard.name'

Presumably I don't have to change my "Station.name" col to "Standard.name", given we're told to call it Station.name in the [guide](https://hugomflavio.github.io/actel-website/manual-data.html#spatial-file)?

Any chance you could LMK what I should do differently? Or does the code need to be tweaked here now actel=TRUE is allowed?

Cheers!

**Comment by dsmith-unbc** [comment]
Hi @SimonDedman , I may be able to help a bit. 

The spatial dataframe needs to be created with the loadSpatial() function (which is given the spatial.csv). 

Also, while actel = TRUE, id.col is ignored so that piece is not necessary. 

If you create the spatial dataframe with loadSpatial(), the Standard.name column should get created. 

Let me know if that helps. 

Cheers,

**Comment by SimonDedman** [comment]
Ok, so, concert existing spatial object into actel-processed spatial object, adds Standard.name column which is where the St.1's come from, solving that conundrum

`spatial <- actel::loadSpatial(spatial)`

then run `distancesMatrix`, presumably don't fix the row & col names with

`colnames(distances) <- spatial$Station.name`

create spatial.txt for all combos of my open array:

```
write.table(x = data.frame(Connection = combn(sort(spatial$Station.name), 2, paste, collapse = " -- ")),
            file = file.path(loadloc, "actel", "processed", "spatial.txt"),
            row.names = FALSE,
            sep = ",")

```

But should I use `spatial$Standard.name` ? Nope, looks like it works fine without. Cheers gents!
