### ISSUE TITLE
Explore/migration/residency functions section legend overlaps titles when there are lots of Sections

### ISSUE THREAD

**Issue by SimonDedman** [hugomflavio/actel#155]
Along similar lines:

![image](https://github.com/user-attachments/assets/f1cd5a8c-b21f-4154-a7c6-96fee119cd87)

The Section legend on the right hand side of the individual detection plots could be sized to avoid overlapping the titles.

**Comment by hugomflavio** [comment]
There are two issues here:

The first is that the array names are too long, which is pushing the  plot label into the caption. Actel probably said `Long array names detected. To improve graphic rendering, consider keeping array names under six characters.` along the way. It would be in the warnings section of the report.

The second issue is that even though actel will automatically fold the legend into two columns once it goes over 14 elements (which happens to be exactly what you have here), it isn't accounting for the fact that "Invalid" is an extra element that may show up, and which should also count towards the number of elements to list when it does. New push coming through to account for this.
