### ISSUE TITLE
Accept ISO 8601 formatted dates in source files

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#30]
Actel's biometrics.csv won't permit dates of the form 'YYYY-MM-DDTHH:mm:ssZ'. Ideally, any ISO-8601 approved format should be equally parseable, and would be supported by any date field across all input files.

**Comment by hugomflavio** [comment]
The "T"-separated format should now be supported. Didn't add support for the format with no dashes (i.e. "YYYYMMDDTHHmmssZ") but that can be easily added later on if requested too.
