### ISSUE TITLE
Signal column in biometrics.csv should allow for multiple codespaces

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#31]
the Signal column in biometrics.csv currently is forced be an integer, but for projects that contain tags across different codespaces, this is not practical. Suggest allowing Signal to be a character string to permit the use of and differentiation between multiple tag codespaces within a study.

**Comment by hugomflavio** [comment]
I see your point, but the main barrier to this is handling different manufacturers (which give different names to the same code spaces). Would love to have a more in-depth chat with you about this when you have a chance.

**Comment by hugomflavio** [comment]
Closing this one for now after our OTN Study Hall discussion :)
