### ISSUE TITLE
Column-based requirements for detection data instead of a pass/fail file-format check

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#32]
Currently detection input is only possible via .csv files in specific manufacturer formats. As telemetry data sharing networks build data exports that contain more information across different projects, they can have more data than a single user's detection files, and are likely to be the preferred input to analysis software.

A clear set of detection file column requirements, would allow users (like me!) to map these files to the proper column headings/formats and use them in the same manner as file exports.

(Later, this will be advantageous to everyone's workflow if we are to attempt to improve cross-compatibility with external telemetry data formats that hold all this information in data frames and not in files at all)

**Comment by hugomflavio** [comment]
To confirm if I understood correctly, you are suggesting a "standard" input format, that is not dependent on any manufacturer specifically? I.e. the possibility to create your own detection files in a format that is provided by the package manual?

That should be easy to include, and it is a great idea!

**Comment by hugomflavio** [comment]
A new internal function is now able to deal with a standard input format, which is explained in the package vignettes:

![image](https://user-images.githubusercontent.com/40389021/83350738-74236d00-a33e-11ea-9a18-aa99cf0264ea.png)

I agree that it would be relevant to implement analyses that do not depend on input files, but rather R objects. On the bright side, all file loading is handled internally by loadStudyData, which should make it somewhat easy to swap it with an R-object-based function instead. But still that will require some time to implement. I think this part would fit better in a new issue.

**Comment by jdpye** [comment]
I was thinking that we let the user specify which column each of these data types can be found in, but having this standard set of expected columns does the same thing for the most part. I'll try to type up a more detailed version of the second ask, maybe aiming for ( https://github.com/vinayudyawer/ATT/ ) ATT as the transitional format.
