### ISSUE TITLE
Don't chop extra columns when parsing detection files / don't use position as column location in processXXXFile()

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#33]
In processVemcoFile it assumes that Timestamp will be the first column in a given detection file. Since the files have headers, the processor should take into account whether a person or a format change has moved the column but still labeled it correctly and use the existing location of the column instead.

**Comment by hugomflavio** [comment]
These seem to be two issues in one:

1) Extra column issue
This is done to ensure all subsets of detections have the same columns (regardless of manufacturer/input file). The column set can be expanded, but it would still be hard to just "include all", as each processXXXFile() run has to return a table with the same column names. A possible work-around would be a function argument specifying the names of the non-standard columns the user is interested in. Which columns were you thinking of?

2) Timestamp column in processVemcoFile
With commit 6734328, processVemcoFile has been updated to look for the timestamp column using `grep("^Date.and.Time", colnames(input))`

**Comment by hugomflavio** [comment]
Using the new preload() function, extra detection columns are no longer ignored
