### ISSUE TITLE
Specify a default action for all filtering queries as part of function call

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#34]
When deciding whether to drop detections from outside deployment ranges, a 'b for all' option should be provided to help people running through the tool on the command line, multiple times, or as part of a script. 

I also wasn't able to find any flags to provide to the analysis functions that would allow me to specify a default response to this question as part of the function call, but for integration of this tool into longer workflows, such a feature would be invaluable.

**Comment by hugomflavio** [comment]
Implemented a new argument to allow the user to automatically discard all orphan detections.

I am currently working on a revamp of the migration analysis to allow it to support inter-section backwards movements. Once I finish that, I will create an option to auto-resolve issues raised by the movement checks too.
