### ISSUE TITLE
Cairo error when building reports on certain Macs

### ISSUE THREAD

**Issue by jdpye** [hugomflavio/actel#62]
Getting an error on some Mac installations at or around this line:

https://github.com/hugomflavio/actel/blob/bc202e6e306f65ef9a222ce160287ec15016bfac/R/print.R#L803

error:
```
In grDevices::svg(paste0(work.path, “times_“, names(times)[i], suffix,  :
  failed to load cairo DLL
```

First instinct from @hugomflavio is to encase this in a try-catch and avoid crashouts on weird and wonderful Mac implementations of R. @jdpye thinks there might be some ways to restore the R environment to restore this specific error, but it would be kinder to catch known errors at this stage in any case.

**Comment by hugomflavio** [comment]
Thanks for creating this issue, @jdpye!
