### ISSUE TITLE
Error running explore()

### ISSUE THREAD

**Issue by joleehaz** [hugomflavio/actel#63]
Hi, I have been following your vignettes, and everything worked brilliantly until I attempted to run `explore(tz = "UTC")`. I keep getting the error message `Error: Not all values in the 'Release.date' column appear to be in a 'yyyy-mm-dd hh:mm' format (seconds are optional). Please double-check the biometrics.`. However, the date is in the correct format, and there were no issues with it when using the `preload()` function. Here is the code I am using followed by the error report as output by the package is below. 

```
biometrics<- read.csv("biometrics.csv")
spatial<- read.csv("spatial.csv")
deployments <- read.csv("deployments.csv")
detections<- read.csv("detections.csv")

library(lubridate)
biometrics$Release.date <- ymd_hm(biometrics$Release.date)

deployments$Start <- ymd_hms(deployments$Start)

deployments$Stop <- ymd_hms(deployments$Stop)

detections$Timestamp <- ymd_hms(detections$Timestamp)

x <- preload(biometrics = biometrics, spatial = spatial, deployments = deployments, 
             detections = detections, tz = "UTC")

explore(tz = "UTC")
```

Actel R package report.
Version: 1.2.1

Target folder: C:/Users/...
Timestamp: 2021-05-28 15:25:43

Function: explore()

M: Importing data. This process may take a while.
Error: Not all values in the 'Release.date' column appear to be in a 'yyyy-mm-dd hh:mm' format (seconds are optional). Please double-check the biometrics.

A fatal exception occurred, stopping the process!
Found a bug? Report it here: https://github.com/hugomflavio/actel/issues

-------------------
Function call:
-------------------
explore(tz = 'UTC', datapack = NULL, max.interval = 60, minimum.detections = 2, start.time = NULL, stop.time = NULL, speed.method = c('last to first'), speed.warning = NULL, speed.error = NULL, jump.warning = 2, jump.error = 3, inactive.warning = NULL, inactive.error = NULL, exclude.tags = NULL, override = NULL, report = FALSE, discard.orphans = FALSE, discard.first = NULL, auto.open = TRUE, save.detections = FALSE, GUI = 'needed', save.tables.locally = 'FALSE, print.releases = TRUE, detections.y.axis = 'auto')

**Comment by hugomflavio** [comment]
Hi! 

Thank you for trying out actel, I hope you are finding it useful :)

Could you send me the biometrics.csv file that is causing the issue?

In the meantime, have you tried using the preloaded object as the input for the explore function? I.e. `explore(datapack = x, tz = "UTC")`

Thanks!

**Comment by joleehaz** [comment]
Hi Hugo,

Thank you so much for getting back to me. It was the datapack = x that was
missing. It is working now I have added it (oops, sorry!).

Best wishes,
Joanna

**Comment by joleehaz** [comment]
Hi Hugo,

Sorry to bother you again, but I have run into another error while
running residency(datapack
= x, tz = "UTC") (log below). Can you offer any advice?

M: Filtering valid array movements.
  |============================================================| 100%
M: Filtering valid section movements.
  |============================================================| 100%
M: Compiling residency objects.
M: Calculating daily locations for each tag.
  |==========================                                  |  43%Error
in colnames(output)[aux - 1][the.zone] :
  invalid subscript type 'list'

M: The analysis errored. You can recover latest the job log (including your
comments and decisions) by running recoverLog().
> recoverLog(x)
Error in file.create(to[okay]) :
  file name conversion problem -- name too long?
In addition: Warning messages:
1: In if (!grepl(".txt$", file)) file <- paste0(file, ".txt") :
  the condition has length > 1 and only the first element will be used
2: In if (file.exists(file) & !overwrite) stop("File '", file, "' already
exists and overwrite = FALSE",  :
  the condition has length > 1 and only the first element will be used
3: In file.create(to[okay]) :
  cannot create file 'list(Release.date = c(1575281100, 1574241600,
1574329680, 1574242620, 1575282600, 1574956680, 1574244000, 1575190740,
1574692920, 1575189240, 1575103260, 1574245380, 1575194100, 1574936820,
1575129240, 1574692140, 1574151240, 1574151960, 1574153100, 1574154000,
1583917020, 1584090120, 1583913840, 1583914260, 1583914920, 1583996640,
1584091260, 1584002100, 1584000900, 1584090660), Serial.nr = c(1326496,
1326497, 1326498, 1326499, 1326500, 1326501, 1326502, 1326503, 1326504,
1326505, 1326506, 1326507,
1326508, 1326509, 1326510, 1326511, 1326512, 1326513, 1326514, 1326515,
1340306, 1340308, 1340309, 1340310, 1340311, 1340312, 1340313, 1340314,
1340316, 1340317), Signal = c(18884, 18885, 18886, 18887, 18888, 18889,
18890, 18891, 18892, 18893, 18894, 18895, 18896, 18897, 18898, 18899,
18900, 18901, 18902, 18903, 57692, 57694, 57695, 57696, 57697, 57698,
57699, 57700, 57702, 57703), Manta.ID = c("CG-MA-0142", "CG-MA-0124",
"CG-MA-0128", "CG-MA-0117", "CG-MA-0161", "CG-MA [... truncated]
4: In file.create(to[okay]) :
  cannot create file 'list(`130000` = list(Receiver = "130000", Array =
"A1", Station.name = "Manta Alley", Standard.name = "St.5", Start =
1575093600, Stop = 1618137000), `130001` = list(Receiver = "130001", Array
= "A1", Station.name = "South Manta Alley", Standard.name = "St.4", Start =
1575093600, Stop = 1618073460), `130002` = list(Receiver = "130002", Array
= "A2", Station.name = "Ile Sudest", Standard.name = "St.1", Start =
1575180000, Stop = 1618072560), `130003` = list(Receiver = "130003", Array
= "A3", Station.name = "Ile Sipaille",
    Standard.name = "St.7", Start = 1574143200, Stop = 1618067700),
`130004` = list(Receiver = "130004", Array = "A4", Station.name = "North
IDR Cleaning Station ", Standard.name = "St.13", Start = 1574143200, Stop =
1618063200), `135384` = list(Receiver = "135384", Array = "A3",
Station.name = "Ile Tattamucca South ", Standard.name = "St.10", Start =
1584252000, Stop = 1620388800), `135385` = list(Receiver = "135385", Array
= "A3", Station.name =  [... truncated]
5: In file.create(to[okay]) :
  cannot create file 'list(stations = list(Station.name = c("Ile Sudest",
"Manta Alley North", "Mid-Manta Alley ", "South Manta Alley", "Manta
Alley", "Ile Sipaille North", "Ile Sipaille", "Carre Pate", "Ile Lubine",
"Ile Tattamucca South ", "lle Tattamucca North ", "Ile des Rats", "North
IDR Cleaning Station "), Latitude = c(-6.696770191, -6.634829998,
-6.6457901, -6.671587, -6.6389207, -6.65444994, -6.668169975, -6.675330162,
-6.676609993, -6.695409775, -6.686339855, -6.643760204, -6.636909962),
Longitude = c(71.39990234,
71.33529663, 71.36460114, 71.393133, 71.3510012, 71.30789948, 71.31900024,
71.34899902, 71.33190155, 71.38200378, 71.36499786, 71.31030273,
71.31529999), Array = c(1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4), Section =
c(1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4), Standard.name = c("St.1", "St.2",
"St.3", "St.4", "St.5", "St.6", "St.7", "St.8", "St.9", "St.10", "St.11",
"St.12", "St.13")), release.sites = list(Station.name = "unspecified",
Longitude = NA, Latitude = NA, Array [... truncated]
6: In file.create(to[okay]) :
  cannot create file 'list(A = c("A2", "A1", "A3"), to = c("--", "--",
"--"), B = c("A1", "A3", "A4")).txt', reason 'Invalid argument'
7: In file.create(to[okay]) :
  cannot create file 'list(A2 = list(neighbours = "A1", before = NULL,
after = "A1", parallel = NULL, edge = TRUE, after.peers = c("A1", "A3",
"A4"), all.after = c("A1", "A3", "A4"), all.after.and.par = c("A1", "A3",
"A4"), live = list(Start = 1575180000, Stop = 1618072560)), A1 =
list(neighbours = c("A3", "A2"), before = "A2", after = "A3", parallel =
NULL, edge = TRUE, before.peers = "A2", all.before = "A2",
all.before.and.par = "A2", after.peers = c("A3", "A4"), all.after = c("A3",
"A4"), all.after.and.par = c("A3",
"A4"), live = list(Start = 1575093600, Stop = 1618154100)), A3 =
list(neighbours = c("A4", "A1"), before = "A1", after = "A4", parallel =
NULL, edge = TRUE, before.peers = c("A1", "A2"), all.before = c("A1",
"A2"), all.before.and.par = c("A1", "A2"), after.peers = "A4", all.after =
"A4", all.after.and.par = "A4", live = list(Start = 1574143200, Stop =
1620388800)), A4 = list(neighbours = "A3", before = "A3", after = NULL,
parallel = NULL, edge = FALSE, before.peers = c("A [... truncated]

Best wishes,
Joanna

**Comment by hugomflavio** [comment]
Hi Joanna,

Glad to see the first problem got solved :)

This second error looks like it could be a real bug. We will have to run actel in debug mode to figure out what is happening. Here is how you can trigger the debug mode:

```r
# This will activate the debug mode
options(actel.debug = TRUE)

[insert your analysis code here]

# If the analysis crashes, go to the folder listed below
# and find the files "actel_debug_file.txt" and "actel.debug.RData"
tempdir()

# alternatively, if you can't find the folder above, copy the two files
# to your current directory so you can access them there:
file.copy(paste0(tempdir(), "/actel_debug_file.txt"), "actel_debug_file.txt")
file.copy(paste0(tempdir(), "/actel.debug.RData"), "actel.debug.RData")

# NOTE: The actel.debug.RData file contains a copy of your study's
# input data, including the detections.

# To deactivate the debug mode again, just run
options(actel.debug = FALSE)
```

Would you be willing to send me the debug files? Note: As stated in the code snippet above, these contain a copy of your input data. I will only use the data for debugging purposes and I will delete it once the problem is found and fixed. If you are willing to share the debug files, could you send them to the email found by running `maintainer('actel')`? If not, perhaps we could arrange a video call, so we can look at the issue together.

On a side note, the argument of recoverLog() is a file name, so when you ran recoverLog(x), you crashed the function. In the future, try recoverLog("crash_log.txt") instead.

**Comment by joleehaz** [comment]
Hi Hugo,

Thank you so much for your help. I managed to get it working; it was my
fault, there was an error in one of the receiver numbers. Sorry to have
troubled you!

Best wishes,
Joanna
