### ISSUE TITLE
jump.warning and jump.error NULL

### ISSUE THREAD

**Issue by sebdalgarno** [hugomflavio/actel#64]
Hi @hugomflavio 
I'm running `residency()` function for the first time on a preloaded datapack. 
I am trying to set jump.warning and jump.error to NULL (as in documentation - "If left NULL (default), no warnings are issued.") but am getting this error:
```
Error: 'jump.warning' must be numeric.
```
Also the documentation for the arguments state that NULL is the default, but the Usage section shows jump.warning = 2 and jump.error = 3 as the defaults.

**Comment by hugomflavio** [comment]
Hi Seb,

Thank you for bringing this to my attention. This is a documentation error (an artefact of copy-pasting text...). I have now updated the documentation of these two arguments. To disable jump warnings, please set jump.warning to Inf, rather than NULL.

 Hugo

**Comment by sebdalgarno** [comment]
awesome thanks!
