### ISSUE TITLE
Add preprocessing features to package

### ISSUE THREAD

**Issue by damianooldoni** [hugomflavio/actel#68]
During a very prolific meeting with @hugomflavio and @PieterjanVerhelst on Oct 29, we compared the work @PieterjanVerhelst and I did to calculate distances along riverways within INBO's [fish-tracking](https://github.com/inbo/fish-tracking/blob/master/scripts/receiver_distance_analysis/Readme.md) repo (not a package!) and the functionalities already implemented by @hugomflavio in this package. We agreed to add to actel some features we developed. Notice all these features are **preprocessing features**.

Here below a descriptive To Do List to implement in several Pull Requests:

- [ ] we agree to this three steps strategy: load shapefiles, plot (optional), rasterize. For this reason, transform the shapefile to raster in a new function called `shapeToRaster()` (quite similar to what we developed in function `shape.to.binary.mask()`). Some refactoring will be needed
- [ ] add function `placeStationsInWater()`: sometimes the stations are not located in the river, but quite far away. _Extending_ the river raster to include them adds a bias in the distance calculation (see details in #69), so should be avoided
- [ ] still, if user prefers to not use placeStationsInWater(), or if the function fails to do what it should do, we could still provide the option to _extend_ the river body just enough to include the stations. This is something we have implemented at **raster level** by turning (small pieces of) land into water. But we cannot put this as a "hidden" step within `placeStationsInWater()` as it acts at raster level. However, I find this approach asymmetric (something I realized today). It should be done at **shapefile level** as this will be much faster and will make workflow easier to understand (something to do by transforming two points into a line/polygon depending on the input shapefile)
- [ ] in our work, we had to deal with river bodies mixing polygons and lines: doing this was possible but some working around were introduced which should be double checked and hopefully removed. The functionality to mix them up could be added to the package
- [ ] write unit-testing using shapefiles (`example_shapefile._`) and stations ([example_spatial.csv](https://github.com/hugomflavio/actel/blob/master/inst/example_spatial.csv)) in [./inst](https://github.com/hugomflavio/actel/tree/master/inst)
- [ ] test actel on the many river bodies used by @PieterjanVerhelst . As we found that the main functionality (calculate distance among stations along riverways) is already included in the package, this should work. In case it doesn't, find the reason and add unit-tests
- [ ] refactor code based on sp to sf has to be done sooner or later: maybe this is the best occasion for doing it? (optional)

**Comment by hugomflavio** [comment]
Closed due to inactivity

**Comment by damianooldoni** [comment]
See #69. But I think it's not realistic for Dec 2022. Of you agree I can put try to plan it for 2023. I will have new tasks from Jan 2023 which still have to be defined. Still, it will for sure be better than now: more freedom especially if it goes on contributing on open software. Let me know. Sorry again for inactivity.

**Comment by hugomflavio** [comment]
No worries. I've closed them for now since we don't expect progress soon, but we can reopen them later on once we know we're about to get things restarted!
