### ISSUE TITLE
Details for implementation of placeStationsInWater() function

### ISSUE THREAD

**Issue by damianooldoni** [hugomflavio/actel#69]
As discussed with @hugomflavio, I summarize specs for developing the `placeStationsInWater()` function which will place stations located out of the river body at the nearest point of the river body:

- function name: `placeStationsInWater`
- check whether the function `geosphere::dist2Line()` used for this projection can be replaced by a function of `gdistance` package
- add a verbose option for getting all info returned, distances to river body included
- return warning mentioning the distance if distance higher than argument distance.warning (buffer): default value 100m?
- return error if distance higher than argument `distance.error`: default value 1km
- check that distance.error >= distance.warning

The interactive map to check the effects of this function is a nice-to-have feature as well and should be added as a plot function where the receivers and the projections are given as a list. In this way we avoid to add leaflet to the actel dependencies. Check [plot.R](https://github.com/hugomflavio/actel/blob/master/R/plot.R).

**Comment by hugomflavio** [comment]
Closed due to inactivity

**Comment by damianooldoni** [comment]
Hi @hugomflavio.
This is still on my official to do list of 2022 even if it got enormously delayed due to too much work for a big European project (which pays my bills) and a second baby born on May 2022.

May I still do it, please? I will do my best to plan it for Dec 2022.
