### ISSUE TITLE
Actel "Error: No valid detection files were found."

### ISSUE THREAD

**Issue by thortb95** [hugomflavio/actel#73]
Hi! My first time with actel.
Trying to run my data

Results <- explore(tz="Europe/Copenhagen")

Why do I get "Error: No valid detection files were found."?

![Skjermbilde 2022-01-31 135940](https://user-images.githubusercontent.com/98750137/151797833-318e1b1c-aa6e-4604-87a2-e4d578a3103c.png)

![Skjermbilde 2022-01-31 135610](https://user-images.githubusercontent.com/98750137/151797845-824544b8-f9ca-4b00-92a5-43661125f174.png)

![Skjermbilde 2022-01-31 135535](https://user-images.githubusercontent.com/98750137/151797852-9f4d5026-2295-4067-9ec7-96c85fa317ea.png)

![Skjermbilde 2022-01-31 135453](https://user-images.githubusercontent.com/98750137/151797859-28bdb612-bd41-42a9-b7fa-2ce4772739e7.png)

**Comment by thortb95** [comment]
Hi! thanks for the answers, I have come further with the analysis, but standing fast here:

I'm trying to run RSP. 
rsp.data <- runRSP(input = explore.Results, t.layer = tl,
         coord.x = "X", coord.y = "Y", recaptures = FALSE)

But got this error 

![image](https://user-images.githubusercontent.com/98750137/152008298-29581e7a-f853-4445-8ea6-a9eae447b6d6.png)

**Comment by hugomflavio** [comment]
Hi! I am glad you found a solution to the detections problem.

What you are facing now is an RSP error (i.e. not an actel error). Please open an issue in RSP's respository, so Yuri can have a look at it and give you some more informed feedback.

Here is the link: https://github.com/YuriNiella/RSP/issues

Thanks!
