### ISSUE TITLE
Date time format error

### ISSUE THREAD

**Issue by PieterjanVerhelst** [hugomflavio/actel#75]
When running the `explore()` function, I get the error that some columns are not in the required `yyyy-mm-dd hh:mm` format. Instead, they have the `dd/mm/yyyy hh:mm` format. When I change the format in excel and save the file, it automatically changes the format again to the former `dd/mm/yyyy hh:mm`. This likely has to do with the settings on my pc. Is there an easy trick to overcome this issue?
Normally I load a file in R and change the date-time to the required format using `lubridate` functionalities, but now the `explore()` function calls on the csv files directly of course.

**Comment by hugomflavio** [comment]
There are three solutions to this:

1) Update the data in R to the correct format and re-save it as a csv. This will allow the traditional `explore()` function to run.
2) Import all data to R, correct it as needed, and use the `preload()` function before calling `explore()`. [More details here](https://cran.r-project.org/web/packages/actel/vignettes/a-3_preload.html).
3) Switch to a more data friendly spreadsheet editor (e.g. [Libreoffice Calc](https://www.libreoffice.org/)) to do the data manipulation.

Hope it helps!

**Comment by PieterjanVerhelst** [comment]
Thanks, I used '1.' to solve the problem.
