### ISSUE TITLE
transitionLayer memory issue

### ISSUE THREAD

**Issue by PieterjanVerhelst** [hugomflavio/actel#76]
I am running the `transitionLayer()` function on a shapefile of 2 MB. However, it returns an error that it cannot allocate a vector of 2.5 GB. Not even after increasing R's memory.
Note that I used a pixel size of 0.001 to generate the raster in `loadShape()`. If I use a lower resolution, the rivers are not visible.

```
> water.shape <- loadShape(path = "./data/external/shapefiles", 
+                          shape = 'be_rivers.shp',
+                          size = 0.001) 
M: Applying a small correction to the shape extent to ensure an integer number of pixels.
M: New shape extent:
       min      max
x  2.54475  7.22675
y 49.49830 53.56030

M: Chosen pixel size: 0.001 
M: Resulting pixel dimensions:
   x    y 
4682 4062 

M: Burning the shape into a raster. This process may take several minutes depending on the shape size and chosen pixel size.
Warning message:
In OGRSpatialRef(dsn, layer, morphFromESRI = morphFromESRI, dumpSRS = dumpSRS,  :
  Discarded datum Reseau_National_Belge_1972 in Proj4 definition: +proj=longlat +ellps=intl +no_defs

> water.transition <- transitionLayer(water.shape, directions = 16)
M: Constructing the transition layer. This process may take several minutes depending on the study area size and chosen pixel size.
Error: cannot allocate vector of size 2.5 Gb
```

**Comment by PieterjanVerhelst** [comment]
I have solved the problem by making the shapefile of the study area smaller. However, this problem may persist when people are trying to run an analysis on a larger study area and hence shapefile.

**Comment by hugomflavio** [comment]
Hi! Sorry for the delay on this one. To solve this, you have to work around the 2.5gb limitation. Either by increasing said limit (something I don't know how to do), or reducing the size of the transition layer. For the latter, you can buffer the river shapefile to artificially enlarge the river lines and use a larger pixel size. You can also reduce the number of allowed directions from 16 to 8 or 4 to reduce the load and make the output smaller in size.

Hope it helps!

**Comment by hugomflavio** [comment]
Closing this one as I believe the situation is resolved.

**Comment by PieterjanVerhelst** [comment]
Indeed, thanks 👍 .
