### ISSUE TITLE
PlotRatios

### ISSUE THREAD

**Issue by thortb95** [hugomflavio/actel#77]
Hi!
I´m trying running plotRatios and this work fine when I just run:
plotRatios(res.results)
![image](https://user-images.githubusercontent.com/98750137/154479205-9c87fb6d-cefc-4ee6-9895-a5536bd3170d.png)

But I get sections I don't want, like "Fjord-River_mouth" and "Fjord-Lake". I select sections: 
plotRatios(res.results, sections = c("Fjord", "River_mouth", "River_mouth-Lake", "Lake"), type = "percentages")
This works, but when I change type to "absolutes" it doesn't work anymore. I also get color by group, something I don't want, I just want the figure without the mentioned sections. Is this possible? :) 

![image](https://user-images.githubusercontent.com/98750137/154480212-56ed99c4-0456-41ef-9f58-d9ddf2f77fb5.png)

**Comment by thortb95** [comment]
Thank u so much for your answers! woho my first bug. I´m waiting :D

**Comment by hugomflavio** [comment]
Update: The error occurs [here](https://github.com/hugomflavio/actel/blob/d5e70c0e35af9596e0d5f1c6c53bf97716e9c387/R/plot.R#L1837). When a group does not show up at one of the required sections, the column doesn't exist, leading to the selection of 'undefined columns'. Changing the matching mechanism will fix this, just got to make sure the system doesn't do partial matches (temporarily making a placeholder column filled with 0's might be safer?). This brings up the need to consider what would happen if the group was not detected at any of the requested sections.

More updates to come.

**Comment by hugomflavio** [comment]
@thortb95 The latest development version should both 1) fix the bug and 2) allow you to chose how to colour the plots using the new `col.by` argument. e.g. `plotRatios(res.results, sections = c("Fjord", "River_mouth", "River_mouth-Lake", "Lake"), type = "percentages", col.by = "section")`

Would you mind trying it out and letting me know how it goes? Follow the instructions below to install the dev version:

```r
# If you don't have the package "remotes" installed, start with:
install.packages("remotes")

# This will install actel's development version:
remotes::install_github("hugomflavio/actel"
			build_opts = c("--no-resave-data", "--no-manual"),
			build_vignettes = TRUE)

library("actel")
# The displayed version should now be 1.2.1.9012
# If that is not the case, unload actel and load it again.
```

Thanks!

**Comment by hugomflavio** [comment]
Closing this one due to inactivity. Hopefully the error is fixed :)
