### ISSUE TITLE
fish detections file mismatch

### ISSUE THREAD

**Issue by haqiqrahmani** [hugomflavio/actel#81]
Greetings, 

I am using fish movement date from the Choctawhachee river and would like to use the approach with Actel. But I get the below error message after running the explore function in Actel package. Would you please help me with this? 

Warning: File 'detections/detections.csv' does not match to any of the supported hydrophone file formats!
         If your file corresponds to a hydrophone log and actel did not recognize it, please get in contact through www.github.com/hugomflavio/actel/issues/new
M: One file was excluded from further analyses.
Error: No valid detection files were found.

Many thanks, 
Haqiq Rahmani
Postdoc research associate 
Wildlife ecology and Conservation 
University of Florida

**Comment by hugomflavio** [comment]
Hi Haqiq,

Thanks for reaching out! It seems actel is having trouble reading your detection files. 

From which manufacturer are your receivers? 

Can you let me know what are the column names in the detections file?

Ultimately, you can always convert your detections into the [standard format supported by actel](https://cran.r-project.org/web/packages/actel/vignettes/a-0_workspace_requirements.html#standard-detections-file). But ideally we would prefer to let actel work with the manufacturer's format directly.

**Comment by hugomflavio** [comment]
Closed due to inactivity
