### ISSUE TITLE
Error in colnames 

### ISSUE THREAD

**Issue by SalmonBiol** [hugomflavio/actel#82]
Hi Hugo,
When running the residency() analysis (timestep = c("hours")) I get the following error... Error in colnames(output)[aux - 1][the.zone] : 
  invalid subscript type 'list'. When I run the residency analysis (timestep = c("days")) I do not get this error. Do you have any suggestions on how best to handle this?

**Comment by hugomflavio** [comment]
Hi Mike,

Thanks for reaching out! Are you running actel 1.2.1? If yes, the first thing I would recommend would be trying the development version. I have corrected a few residency bugs, this might be one of them.

Here's the code to install the dev version:

```r
remotes::install_github("hugomflavio/actel"
			build_opts = c("--no-resave-data", "--no-manual"), 
			build_vignettes = TRUE)
```

After installing it, the next time you load actel it should say v.1.2.1.9015

Let me know how it goes!

**Comment by hugomflavio** [comment]
Closed due to inactivity
