### ISSUE TITLE
Missed event counts/efficiencies

### ISSUE THREAD

**Issue by jessicas09** [hugomflavio/actel#84]
I'm receiving a few warnings during the initial Residency analysis that my animals "jumped" through arrays. However, it's not calculating the missed events/efficiencies. There are many recorded events, but there is a '-' for the Known Missed Events and Potentially Missed Events. Many of my receivers are connected which I have specified in the spatial.txt file), but they're not _all_ connected. Given that I'm getting warnings of animals jumping, shouldn't the missed events + efficiencies be calculated? I've read through the vignette but it seems like I should be getting some #'s for those calculations.

(or do I need to render each one of the "jumps" as invalid for it to count?)

**Comment by hugomflavio** [comment]
Can I see the spatial.txt file and some examples of the jump warnings? You don't need to invalidate the jumps, potentially something else is preventing the efficiency calculation. I need some more info to investigate :)

**Comment by jessicas09** [comment]
Oh yes! Let me know if you need anything else :)

![Screen Shot 2022-12-07 at 4 17 23 PM](https://user-images.githubusercontent.com/119961401/206325369-bb6c579d-2131-40bf-ba10-522522e1413c.png)

![Screen Shot 2022-12-07 at 4 16 20 PM](https://user-images.githubusercontent.com/119961401/206325240-81196549-5d2d-4432-91de-7cc9fa914ce1.png)

**Comment by hugomflavio** [comment]
Any chance you could copy-paste the contents of the spatial.txt here just so I don't have to manually write them down? 😅

**Comment by hugomflavio** [comment]
all the connections between the arrays are doubled. If you write both `WB6 -- WB7` and `WB7 -- WB6`, you are telling actel that the two arrays are parallel (which in turn makes efficiency calculations impossible).

Try with this spatial txt instead:

```
WB6 -- WB7
WB6 -- WB8

WB7 -- WB8
WB7 -- WB13
WB7 -- WB10

WB8 -- WB10
WB8 -- WB13

WB10 -- WB13
WB10 -- WB11

WB11 -- WB13
WB11 -- WB12
```

You can visualise the difference between the two with these two diagrams:

Your spatial.txt file:

![image](https://user-images.githubusercontent.com/40389021/206328330-3226a816-01ff-4b34-a526-8e86c53782bd.png)


The new spatial.txt file:

![image](https://user-images.githubusercontent.com/40389021/206328357-ff3356f8-780e-4d30-8fb7-62762d03c299.png)



(note: the plotDot function I used to make the two diagrams above is not yet available to the public but I aim to publish it in the future)


Please try again and let me know how it goes :) Efficiency calculations are finicky... but hopefully this will fix it.

**Comment by jessicas09** [comment]
That worked - thank you!!! Appreciate you!
