### ISSUE TITLE
Actel did not recognize detection files

### ISSUE THREAD

**Issue by Jet2191** [hugomflavio/actel#99]
Hi, 
I'm trying to process INNOVASEA data from VR2Tx and VR2W receivers using Actel 1.3.0.9007 but I get the warning;
'Warning: File 'detections.csv' does not match to any of the supported hydrophone file formats!
         If your file corresponds to a hydrophone log and actel did not recognize it, please get in contact through www.github.com/hugomflavio/actel/issues/new'

I think I put all the data in the input data formats described on your website. 

[biometrics.csv](https://github.com/user-attachments/files/16541416/biometrics.csv)
[deployments.csv](https://github.com/user-attachments/files/16541417/deployments.csv)
[detections.csv](https://github.com/user-attachments/files/16541419/detections.csv)
[spatial.csv](https://github.com/user-attachments/files/16541420/spatial.csv)

Curious to hear what you think. Thanks in advance. 
Kind regards, 
Jet

**Comment by hugomflavio** [comment]
Hi Jet!

It seems that your detections file is missing the code space column. If you add that column, actel should stop complaining about the file. Let me know if that doesn't happen.

Hugo

**Comment by Jet2191** [comment]
> Hi Jet!
> 
> It seems that your detections file is missing the code space column. If you add that column, actel should stop complaining about the file. Let me know if that doesn't happen.
> 
> Hugo

That worked. Thank you so much. Super exciting!

**Comment by hugomflavio** [comment]
Awesome :) Good luck with your analysis!
